[package]
name = "rye"
version = "0.0.0"
publish = false
description = """
Catch2 inspired testing framework for Rust
"""
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ubnt-intrepid/joke-rs.git"
readme = "README.md"

[dependencies]
cfg-if = "0.1"
futures-core = { version = "0.3", optional = true }
pin-project = { version = "0.4", optional = true }
rye-macros = { path = "macros" }

[dev-dependencies]
futures-executor = "0.3"
futures-test = "0.3"

[features]
default = [ "futures" ]
futures = [ "futures-core", "pin-project" ]
nightly = []

[workspace]
members = [
  ".",
  "macros",
]
