[package]
name = "rye"
version = "0.1.0-dev"
description = """
A custom unit testing framework inspired by Catch2.
"""
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ubnt-intrepid/rye.git"
readme = "README.md"

[features]
frameworks = []

[dependencies]
rye-macros = { version = "=0.1.0-dev", path = "./macros" }
futures = "0.3"
maplit = "1"
pin-project = "0.4"

[dev-dependencies]
rye-runner = { path = "runner" }
anyhow = "1"
futures-test = "0.3"
scoped-tls = "1"
trybuild = "1"

[dev-dependencies.cargo-husky]
version = "1.5"
features = [ "user-hooks" ]
default-features = false

[[test]]
name = "test_integration"
path = "tests/test_integration.rs"
harness = false

[[test]]
name = "test_frameworks"
path = "tests/test_frameworks.rs"
required-features = [ "frameworks" ]

[workspace]
members = [
  ".",
  "macros",
  "runner",
]
