[package]
name = "rye"
version = "0.0.1"
description = """
A custom unit testing framework inspired by Catch2.
"""
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ubnt-intrepid/rye.git"
readme = "README.md"

[dependencies]
rye-macros = { version = "=0.0.1", path = "./macros" }
expected = { version = "0.0.1", features = [ "futures" ] }
futures = { version = "0.3", features = [ "thread-pool" ] }
maplit = "1"
maybe-unwind = { version = "0.1", features = [ "futures" ] }
mimicaw = "0.1.3"
pin-project = "0.4"

[dev-dependencies]
futures-test = "0.3"
scoped-tls = "1"
trybuild = "1"

[dev-dependencies.cargo-husky]
version = "1.5"
features = [ "user-hooks" ]
default-features = false

[[test]]
name = "test_integration"
path = "tests/test_integration.rs"
harness = false

[workspace]
members = [
  ".",
  "macros",
]
