[package]
name = "rye"
version = "0.0.0"
publish = false
description = """
A Rust unit testing library inspired by Catch2.
"""
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ubnt-intrepid/joke-rs.git"
readme = "README.md"

[dependencies]
rye-macros = { path = "macros" }
futures-core = { version = "0.3", optional = true }
pin-project = { version = "0.4", optional = true }

[dev-dependencies]
futures-executor = "0.3"
futures-test = "0.3"
scoped-tls = "1"
trybuild = "1"

[features]
default = [ "futures" ]
futures = [ "futures-core", "pin-project" ]

[dev-dependencies.cargo-husky]
version = "1.5"
features = [ "user-hooks" ]
default-features = false

[workspace]
members = [
  ".",
  "macros",
]
