[package]
name = "rye-xtask"
version = "0.0.0"
publish = false
edition = "2018"

[[bin]]
name = "xtask"
path = "src/main.rs"

[dependencies]
anyhow = "1"
fakeenv = { version = "0.1", default-features = false, features = [ "fake" ] }
pico-args = "0.3"
version_check = "0.9"
