[package]
name = "rye-xtask"
version = "0.0.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1"
pico-args = "0.3"

[dev-dependencies.cargo-husky]
version = "1.5"
features = [ "user-hooks" ]
default-features = false
