[package]
name = "rye-xtask"
version = "0.0.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1"
pico-args = "0.3"
version_check = "0.9"
walkdir = "2"

[dependencies.cargo-husky]
version = "1.5"
features = [ "user-hooks" ]
default-features = false
