[package]
name = "compiletest"
version = "0.0.0"
publish = false
edition = "2018"

[workspace]

[dev-dependencies]
trybuild = "1"

[dev-dependencies.rye]
path = "../../crates/rye"
default-features = false
