[package]
name = "test-frameworks"
version = "0.0.0"
publish = false
edition = "2018"

[workspace]

[dev-dependencies]
rye = { path = "../../rye", default-features = false, features = [ "frameworks" ] }
anyhow = "1"
