[package]
name = "rye-macros"
version = "0.0.0"
publish = false
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features = [ "full", "visit-mut" ] }
quote = "1"
proc-macro2 = "1"
