name: Doc

on:
  push:
    branches:
      - master

jobs:
  Doc:
    runs-on: ubuntu-18.04
    container:
      image: rustops/crates-build-env:latest
      options: --memory 3221225472

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true

    - name: Install mdbook
      run: |
        MDBOOK_VERSION=0.3.7
        URL=https://github.com/rust-lang/mdBook/releases/download/v${MDBOOK_VERSION}/mdbook-v${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz
        mkdir -pv $HOME/.cargo/bin
        curl -sSL $URL | tar xzvf - -C $HOME/.cargo/bin
        echo ::add-path::$HOME/.cargo/bin

    - name: Check tools installation
      run: |
        cargo --version
        rustc --version
        mdbook --version

    - name: Generate Cargo.lock
      run: cargo generate-lockfile

    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Fetch cargo dependencies
      run: cargo fetch

    # TODO:
    # * restrict all write access expect target/
    - name: Build API docs
      run: cargo xtask doc

    - name: Deply to GitHub Pages
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./target/doc
        force_orphan: true
