name: CI

on:
  push:
    branches:
      - master
      - staging
      - trying

env:
  CARGO_HUSKY_DONT_INSTALL_HOOKS: true
  CARGO_TERM_VERBOSE: true

jobs:
  Test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Install Rust toolchains
      run: |
        rustup set profile minimal
        rustup install stable beta nightly 1.40.0

    - name: Install Wasmtime tools
      if: "!contains(runner.os, 'windows')"
      run: |
        curl https://wasmtime.dev/install.sh -sSf | bash
        echo ::set-env name=WASMTIME_HOME::$HOME/.wasmtime
        echo ::add-path::$HOME/.wasmtime/bin
        cargo +stable install --debug cargo-wasi

    - name: Test Wasmtime installation
      if: "!contains(runner.os, 'windows')"
      run: wasmtime --version

    - name: Correct permissions
      if: contains(runner.os, 'Linux')
      run: sudo chown -R $(whoami):$(id -ng) ~/.cargo/

    - name: Generate Cargo.lock
      run: cargo generate-lockfile

    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

    - name: Fetch cargo dependencies
      run: cargo fetch

    - name: Run Lint
      run: cargo +stable xtask lint

    - name: Run CI test (stable)
      run: cargo +stable xtask test
      env:
        RUSTFLAGS: "-D warnings"

    - name: Run CI test (beta)
      run: cargo +beta xtask test
      env:
        RUSTFLAGS: "-D warnings"

    - name: Run CI test (minimal supported toolchain)
      run: cargo +1.40.0 xtask test
      env:
        RUSTFLAGS: "-D warnings"

    - name: Run CI test (nightly)
      run: cargo +nightly xtask test
